# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cal.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(375, 396)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./cal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lcd = QtGui.QLCDNumber(Dialog)
        self.lcd.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcd.setSmallDecimalPoint(False)
        self.lcd.setDigitCount(8)
        self.lcd.setObjectName(_fromUtf8("lcd"))
        self.verticalLayout_2.addWidget(self.lcd)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.b1 = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b1.setFont(font)
        self.b1.setObjectName(_fromUtf8("b1"))
        self.horizontalLayout.addWidget(self.b1)
        self.b2 = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b2.setFont(font)
        self.b2.setObjectName(_fromUtf8("b2"))
        self.horizontalLayout.addWidget(self.b2)
        self.b3 = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b3.setFont(font)
        self.b3.setObjectName(_fromUtf8("b3"))
        self.horizontalLayout.addWidget(self.b3)
        self.b_plus = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b_plus.setFont(font)
        self.b_plus.setObjectName(_fromUtf8("b_plus"))
        self.horizontalLayout.addWidget(self.b_plus)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.b4 = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b4.setFont(font)
        self.b4.setObjectName(_fromUtf8("b4"))
        self.horizontalLayout_2.addWidget(self.b4)
        self.b5 = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b5.setFont(font)
        self.b5.setObjectName(_fromUtf8("b5"))
        self.horizontalLayout_2.addWidget(self.b5)
        self.b6 = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b6.setFont(font)
        self.b6.setObjectName(_fromUtf8("b6"))
        self.horizontalLayout_2.addWidget(self.b6)
        self.b_sub = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b_sub.setFont(font)
        self.b_sub.setObjectName(_fromUtf8("b_sub"))
        self.horizontalLayout_2.addWidget(self.b_sub)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.b7 = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b7.setFont(font)
        self.b7.setObjectName(_fromUtf8("b7"))
        self.horizontalLayout_3.addWidget(self.b7)
        self.b8 = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b8.setFont(font)
        self.b8.setObjectName(_fromUtf8("b8"))
        self.horizontalLayout_3.addWidget(self.b8)
        self.b9 = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b9.setFont(font)
        self.b9.setObjectName(_fromUtf8("b9"))
        self.horizontalLayout_3.addWidget(self.b9)
        self.b_mul = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b_mul.setFont(font)
        self.b_mul.setObjectName(_fromUtf8("b_mul"))
        self.horizontalLayout_3.addWidget(self.b_mul)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.b0 = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b0.setFont(font)
        self.b0.setObjectName(_fromUtf8("b0"))
        self.horizontalLayout_4.addWidget(self.b0)
        self.b_pont = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b_pont.setFont(font)
        self.b_pont.setObjectName(_fromUtf8("b_pont"))
        self.horizontalLayout_4.addWidget(self.b_pont)
        self.b_clear = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b_clear.setFont(font)
        self.b_clear.setObjectName(_fromUtf8("b_clear"))
        self.horizontalLayout_4.addWidget(self.b_clear)
        self.b_div = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b_div.setFont(font)
        self.b_div.setObjectName(_fromUtf8("b_div"))
        self.horizontalLayout_4.addWidget(self.b_div)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.b_eq = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        self.b_eq.setFont(font)
        self.b_eq.setObjectName(_fromUtf8("b_eq"))
        self.verticalLayout.addWidget(self.b_eq)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "计算器", None))
        Dialog.setWhatsThis(_translate("Dialog", "计算器", None))
        self.b1.setText(_translate("Dialog", "1", None))
        self.b2.setText(_translate("Dialog", "2", None))
        self.b3.setText(_translate("Dialog", "3", None))
        self.b_plus.setText(_translate("Dialog", "+", None))
        self.b4.setText(_translate("Dialog", "4", None))
        self.b5.setText(_translate("Dialog", "5", None))
        self.b6.setText(_translate("Dialog", "6", None))
        self.b_sub.setText(_translate("Dialog", "-", None))
        self.b7.setText(_translate("Dialog", "7", None))
        self.b8.setText(_translate("Dialog", "8", None))
        self.b9.setText(_translate("Dialog", "9", None))
        self.b_mul.setText(_translate("Dialog", "*", None))
        self.b0.setText(_translate("Dialog", "0", None))
        self.b_pont.setText(_translate("Dialog", ".", None))
        self.b_clear.setText(_translate("Dialog", "清除", None))
        self.b_div.setText(_translate("Dialog", "/", None))
        self.b_eq.setText(_translate("Dialog", "=", None))

